-- 015_research_activity.sql
--
-- Who is doing the R&D, on what, and at what maturity.
--
-- WHY THIS TABLE EXISTS AND THE PLANNED ONE DOES NOT
-- ==================================================
-- The plan for 2026-09-14 was `015_organization_technologies.sql`: an
-- edge from `organizations` to `technologies`, populated from TechPort.
-- The survey that was supposed to justify it killed it instead.
--
-- Two runs, 50 projects each, against 19,690:
--
--     leadOrganization present              100%
--     a primary taxonomy node               94%
--     trlCurrent present                    76%
--     all three on ONE project              70%
--     distinct lead orgs matching `organizations`   1 of 35  (3%)
--
-- The data is there. The join is not. And the unmatched list is the
-- argument rather than the rate: Johnson, JPL, Ames, Kennedy - then
-- Apptronik, Tendeg, Creare, VIP Sensors, Iris Technology, GeoVisual.
-- Firms that have never operated a spacecraft, which is precisely why an
-- operator catalogue has no reason to name them.
--
-- Loosening the rule confirms it rather than fixing it: the five extra
-- matches from stripping an agency prefix are GSFC, Glenn, Langley,
-- Marshall. More NASA centres, no companies.
--
--   > TechPort names who does the R&D.  GCAT names who operates the
--   > hardware.  Different populations (AD-083).
--
-- AD-084 then made R&D a tracked aspect of technology in its own right,
-- which turns that result from a dead end into a layer. The platform
-- already measures what an organisation OPERATES (GCAT, 011) and what it
-- PRODUCES (014). What it ADVANCES is a third thing, and nothing before
-- this migration captured it.
--
-- THE LINK TO `organizations` IS AN ATTRIBUTE, NEVER THE SPINE
-- ===========================================================
-- `research_organizations.organization_code` is NULLABLE and nothing
-- requires it (AD-085). NULL is the normal case - 97% of the time - not
-- a failure to be cleaned up later.
--
-- Making that column the join key would discard 97% of the R&D evidence
-- to preserve a spine that was never the right one for this question.
-- This is the same restraint 011 applied to `parent_code`: keep the
-- source's own identity losslessly, and resolve into ours only where the
-- resolution is confident.
--
-- WHAT THIS REFUSES TO DO
-- =======================
-- `research_projects.trl_current` NEVER writes to `technologies.trl`
-- (AD-061). It describes a FUNDED PROJECT, not a technology, and several
-- projects on one technology legitimately differ - each states where
-- THAT project's work sits, not where the state of the art is. The
-- highest trl_current across projects mapped to a technology is evidence
-- that someone took it that far; disagreement with a curated value is a
-- finding, never an automatic correction.
--
-- There is also no link from a project to `technologies` in this
-- migration at all. That join is fuzzy - name to title and taxonomy, no
-- shared key - and AD-062 requires it be surveyed with a predicted match
-- rate before it is built. One fuzzy join at a time.
--
-- ATTRIBUTION IS A CONDITION OF USE
-- =================================
-- NASA content is generally not subject to US copyright and asks for
-- acknowledgement rather than permission (AD-060). The credit must
-- render BEFORE the first TechPort-derived value does, not after. The
-- exact string is carried in the table comment below so the API can
-- serve it rather than a developer retyping it.
--
-- AN OPEN QUESTION, RECORDED RATHER THAN GUESSED
-- ==============================================
-- TechPort's `leadOrganization` is an object. The survey extracted
-- `organizationName` from it and nothing else, so it is NOT KNOWN
-- whether it carries a stable organisation id. Rather than design a
-- primary key on a field nobody has looked at - the exact mistake the
-- 09-11 plan made and 09-12 corrected - this table uses a surrogate key
-- with a UNIQUE normalised name, and reserves `techport_org_id` for the
-- day the importer's survey answers the question. When it does, the FK
-- does not have to change.


-- ── R&D performers ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS research_organizations (
    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    name          TEXT NOT NULL,
    -- Lowercased, punctuation and corporate suffixes removed. The upsert
    -- key today. Generated by the importer rather than here because the
    -- normalisation rules live beside the matcher that has to agree with
    -- them (`norm()` in check_techport.py), and two implementations of
    -- one rule is how they drift.
    name_norm     TEXT NOT NULL,

    org_type      TEXT,          -- TechPort's own vocabulary, kept verbatim

    -- Reserved. See "AN OPEN QUESTION" above. UNIQUE so that populating
    -- it later cannot silently create duplicates.
    techport_org_id BIGINT,

    -- ── The attribute, not the spine (AD-085) ──
    -- NULL is the normal case. ~3% strict, ~28% of projects once NASA
    -- field centres are allowed through an agency-prefix strip.
    organization_code TEXT REFERENCES organizations (code),
    -- 'strict' | 'agency_prefix_stripped' | NULL. Which rule matched is
    -- part of the claim: 013 and the GCAT work both learned that a match
    -- made under a loosened rule has to stay distinguishable from one
    -- made under the strict rule, or the loosening becomes invisible.
    match_method      TEXT,
    source_confidence REAL,
    matched_at        TIMESTAMPTZ,

    data_source   TEXT NOT NULL DEFAULT 'techport',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT research_org_name_norm_key UNIQUE (name_norm),
    CONSTRAINT research_org_techport_id_key UNIQUE (techport_org_id),
    -- A match_method without a code, or a code without a method, means
    -- one of the two writes was lost. Neither is a state the importer
    -- can produce on purpose.
    CONSTRAINT research_org_match_complete CHECK (
        (organization_code IS NULL AND match_method IS NULL)
        OR (organization_code IS NOT NULL AND match_method IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_research_org_code
    ON research_organizations (organization_code)
    WHERE organization_code IS NOT NULL;


-- ── Funded projects ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS research_projects (
    -- TechPort's key, not a surrogate. The same choice 011 made with
    -- GCAT's org code and 005 with norad_id: where the source has a
    -- stable identifier, it is the primary key, so a re-import is an
    -- upsert rather than a diff.
    techport_id   BIGINT PRIMARY KEY,

    title         TEXT NOT NULL,
    status        TEXT,
    start_date    DATE,
    end_date      DATE,

    -- 76% carry one. NULL is ordinary and must not exclude the project:
    -- a project with no TRL still tells you who is working on what.
    trl_current   SMALLINT,

    lead_org_id   BIGINT REFERENCES research_organizations (id),

    -- TechPort's own field. Two jobs: the cache TTL compares against it,
    -- and a re-import can skip a project whose source has not moved.
    last_updated  DATE,

    data_source   TEXT NOT NULL DEFAULT 'techport',
    fetched_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT research_project_trl_range CHECK (
        trl_current IS NULL OR trl_current BETWEEN 1 AND 9
    ),
    CONSTRAINT research_project_dates CHECK (
        start_date IS NULL OR end_date IS NULL OR end_date >= start_date
    )
);

CREATE INDEX IF NOT EXISTS idx_research_proj_org ON research_projects (lead_org_id);
CREATE INDEX IF NOT EXISTS idx_research_proj_trl ON research_projects (trl_current)
    WHERE trl_current IS NOT NULL;


-- ── Taxonomy, at the depth the source actually uses ──────────────────
--
-- MEASURED, NOT ASSUMED: of 47 primary nodes in the 09-14 sample, 42 sit
-- at depth 3 (TX11.6.4 Quantum Computer), 4 at top level, 1 at depth 2.
-- All 47 carried a code, which is why `tx_code` is NOT NULL here - that
-- is a measurement, and if a codeless node ever appears the importer
-- must report it rather than write a NULL nobody notices.
--
-- `tx_top` is GENERATED from the code (AD-086). It is not a column the
-- importer fills, because the failure this prevents is subtle: a column
-- mixing TX08 with TX08.1.5 groups silently and WRONGLY, both are
-- titles, and only the code distinguishes them. Generating it is the
-- same reasoning as technologies.readiness_gap and organizations
-- .display_name - a derived value computed where it cannot drift from
-- its input.

CREATE TABLE IF NOT EXISTS research_project_taxonomy (
    techport_id   BIGINT NOT NULL
                  REFERENCES research_projects (techport_id) ON DELETE CASCADE,
    tx_code       TEXT NOT NULL,
    tx_title      TEXT NOT NULL,

    tx_top        TEXT GENERATED ALWAYS AS (split_part(tx_code, '.', 1)) STORED,

    PRIMARY KEY (techport_id, tx_code),

    -- THE CONTROL THAT CAN GO RED.
    -- If a parser ever writes a node's title into the code column - the
    -- precise defect AD-086 exists to prevent, and the one the first
    -- survey shipped by keeping `title` and discarding `code` - this
    -- rejects the row at write time instead of producing a taxonomy
    -- that groups by accident.
    CONSTRAINT research_tx_code_shape CHECK (tx_code ~ '^TX[0-9]{2}(\.[0-9]+)*$')
);

CREATE INDEX IF NOT EXISTS idx_research_tx_top ON research_project_taxonomy (tx_top);


-- ── Comments ─────────────────────────────────────────────────────────

COMMENT ON TABLE research_organizations IS
    'R&D performers as NASA TechPort names them - field centres, '
    'universities, primes and SBIR-stage firms. A DIFFERENT POPULATION '
    'from `organizations`, which names who operates hardware in orbit: '
    'one distinct name in thirty-five matches (AD-083). '
    'Source: NASA TechPort (https://techport.nasa.gov). NASA content is '
    'not subject to US copyright; acknowledgement is required wherever '
    'it is displayed (AD-060).';

COMMENT ON COLUMN research_organizations.organization_code IS
    'Optional link to the operator catalogue. AN ATTRIBUTE, NEVER THE '
    'JOIN KEY (AD-085). NULL for ~97% of performers and that is the '
    'normal case, not a backlog.';

COMMENT ON COLUMN research_organizations.techport_org_id IS
    'Reserved. It is not yet established whether TechPort''s '
    'leadOrganization object carries a stable id; the survey read only '
    'organizationName. Populate once the importer''s survey answers it - '
    'the FK does not change when it does.';

COMMENT ON TABLE research_projects IS
    'One funded NASA TechPort project. NOT a technology: trl_current '
    'describes THIS project''s work, and several projects on one '
    'technology legitimately differ (AD-061). Never written to '
    'technologies.trl.';

COMMENT ON COLUMN research_projects.trl_current IS
    'Present on ~76%. NULL is ordinary - a project with no stated TRL '
    'still says who is working on what.';

COMMENT ON TABLE research_project_taxonomy IS
    'NASA TX taxonomy nodes, at the depth TechPort uses (42 of 47 at '
    'depth 3). tx_top is GENERATED by code prefix: grouping by title '
    'mixes TX08 with TX08.1.5 silently and wrongly (AD-086).';


-- ── Views ────────────────────────────────────────────────────────────
--
-- security_invoker so the caller's own privileges apply. 010 set this on
-- the three views that predated it; every view since is born with it.

CREATE OR REPLACE VIEW research_activity_by_area
WITH (security_invoker = true) AS
SELECT
    t.tx_top                                    AS tx_area,
    count(DISTINCT p.techport_id)               AS projects,
    count(DISTINCT p.lead_org_id)               AS performers,
    count(p.trl_current)                        AS projects_with_trl,
    min(p.trl_current)                          AS trl_min,
    max(p.trl_current)                          AS trl_max,
    -- Reported for shape, and deliberately NOT rounded into a level.
    -- An average TRL across separately-funded projects is a summary of
    -- activity, not an assessment of a technology (AD-061).
    round(avg(p.trl_current)::numeric, 1)       AS trl_mean
FROM research_project_taxonomy t
JOIN research_projects p USING (techport_id)
GROUP BY t.tx_top;

CREATE OR REPLACE VIEW research_organization_summary
WITH (security_invoker = true) AS
SELECT
    o.id,
    o.name,
    o.org_type,
    o.organization_code,
    o.match_method,
    count(p.techport_id)                        AS projects,
    count(p.trl_current)                        AS projects_with_trl,
    max(p.trl_current)                          AS trl_max,
    max(p.last_updated)                         AS most_recent_project
FROM research_organizations o
LEFT JOIN research_projects p ON p.lead_org_id = o.id
GROUP BY o.id, o.name, o.org_type, o.organization_code, o.match_method;

COMMENT ON VIEW research_activity_by_area IS
    'R&D activity per TX top-level area. Grouped on the GENERATED '
    'tx_top, never on a node title.';

COMMENT ON VIEW research_organization_summary IS
    'Per performer. LEFT JOIN on purpose: a performer with no project '
    'rows is a bug worth seeing, not a row worth hiding.';


-- ── Access ───────────────────────────────────────────────────────────

ALTER TABLE research_organizations     ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_projects          ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_project_taxonomy  ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read research_organizations" ON research_organizations;
CREATE POLICY "Public read research_organizations"
    ON research_organizations FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read research_projects" ON research_projects;
CREATE POLICY "Public read research_projects"
    ON research_projects FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read research_project_taxonomy" ON research_project_taxonomy;
CREATE POLICY "Public read research_project_taxonomy"
    ON research_project_taxonomy FOR SELECT USING (true);

GRANT SELECT ON research_organizations        TO anon;
GRANT SELECT ON research_projects             TO anon;
GRANT SELECT ON research_project_taxonomy     TO anon;
GRANT SELECT ON research_activity_by_area     TO anon;
GRANT SELECT ON research_organization_summary TO anon;

-- 010 revoked these at schema level and set ALTER DEFAULT PRIVILEGES, so
-- a new table should not be born with them. Stated anyway, for the same
-- reason 011 states it: "should not" is a belief until something checks,
-- and tests/test_db_privileges.py is what checks.
REVOKE TRUNCATE, TRIGGER, REFERENCES ON research_organizations        FROM anon, authenticated;
REVOKE TRUNCATE, TRIGGER, REFERENCES ON research_projects             FROM anon, authenticated;
REVOKE TRUNCATE, TRIGGER, REFERENCES ON research_project_taxonomy     FROM anon, authenticated;
REVOKE TRUNCATE, TRIGGER, REFERENCES ON research_activity_by_area     FROM anon, authenticated;
REVOKE TRUNCATE, TRIGGER, REFERENCES ON research_organization_summary FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON research_organizations       FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON research_projects            FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON research_project_taxonomy    FROM anon, authenticated;

-- Verify:
--
--   -- the shape control actually refuses a title in the code column
--   INSERT INTO research_project_taxonomy (techport_id, tx_code, tx_title)
--   VALUES (1, 'Sensors and Instruments', 'x');   -- expect CHECK violation
--
--   -- tx_top is derived, never supplied
--   SELECT tx_code, tx_top FROM research_project_taxonomy LIMIT 5;
--
--   -- the attribute is mostly NULL, and that is correct
--   SELECT count(*) FILTER (WHERE organization_code IS NOT NULL) AS linked,
--          count(*) AS total
--   FROM research_organizations;
