-- 017_taxonomy_other_nodes.sql
--
-- `X` is a real taxonomy segment. 015's CHECK was refusing it.
--
-- WHAT THE FIRST IMPORT REPORTED
-- ==============================
-- The first 500-project run listed five taxonomy nodes it had refused:
--
--     TX14.X  Other Thermal Management Systems
--     TX11.X  Other Software, Modeling, Simulation...
--     TX08.X  Other Sensors and Instruments
--
-- Those are NASA's own "Other" buckets within a top-level area, not
-- malformed data. 015's `^TX[0-9]{2}(\.[0-9]+)*$` allowed only digits
-- after the prefix, so it was discarding legitimate taxonomy - quietly,
-- had the importer not been built to list what it refuses.
--
-- MEASURED BEFORE RELAXING
-- ========================
-- Across 548 cached project details: 518 codes strict, 5 with `.X`, and
-- NOTHING else. Zero nodes of any other shape. So this relaxes the
-- constraint to exactly what the source uses rather than to whatever
-- might one day turn up - the pattern still refuses a title in the code
-- column, which is the defect it exists for (AD-086).
--
-- `tx_top` is unaffected: split_part('TX14.X', '.', 1) is 'TX14', so
-- "Other Sensors and Instruments" has always rolled up to TX08
-- correctly. It was the CHECK that was wrong, not the derivation.
--
-- NOTHING NEEDS BACKFILLING FROM THE API. The five refused nodes were
-- never written, and every project detail is held in
-- data/cache/techport, so `seed_techport --apply --refresh` re-parses
-- rows already imported at a cost of zero requests.

ALTER TABLE research_project_taxonomy
    DROP CONSTRAINT IF EXISTS research_tx_code_shape;

ALTER TABLE research_project_taxonomy
    ADD CONSTRAINT research_tx_code_shape
    CHECK (tx_code ~ '^TX[0-9]{2}(\.([0-9]+|X))*$');

COMMENT ON TABLE research_project_taxonomy IS
    'NASA TX taxonomy nodes, at the depth TechPort uses (42 of 47 at '
    'depth 3 in the 09-14 sample). tx_top is GENERATED by code prefix: '
    'grouping by title mixes TX08 with TX08.1.5 silently and wrongly '
    '(AD-086). A segment of `X` is NASA''s "Other" bucket and is valid '
    '(017); measured at 5 of 523 nodes.';

-- Verify:
--
--   -- the Other buckets are now storable
--   INSERT INTO research_project_taxonomy (techport_id, tx_code, tx_title)
--   VALUES (<an existing id>, 'TX14.X', 'Other Thermal Management');
--
--   -- and a title in the code column is still refused
--   INSERT INTO research_project_taxonomy (techport_id, tx_code, tx_title)
--   VALUES (<an existing id>, 'Sensors and Instruments', 'x');
--
--   -- rollup unchanged
--   SELECT tx_code, tx_top FROM research_project_taxonomy
--    WHERE tx_code LIKE '%.X';     -- expect TX14.X -> TX14
